--CREAR LOGIN
CREATE LOGIN USUARIO
WITH PASSWORD = 'PASSWORD';
GO

--BASE DE DATOS
CREATE DATABASE BD_TRANSACCIONES_LDCC;
GO

--DBO
ALTER AUTHORIZATION ON DATABASE::BD_TRANSACCIONES_LDCC
TO USUARIO;
GO

USE BD_TRANSACCIONES_LDCC;
GO


-- TABLA MONEDA
CREATE TABLE MONEDA (
    CODIGO CHAR(3) NOT NULL,
    NOMBRE NVARCHAR(20) NOT NULL,

    CONSTRAINT PK_MONEDA
        PRIMARY KEY (CODIGO)

);

GO

--TABLA CUENTA
CREATE TABLE CUENTA (
    NRO_CUENTA NVARCHAR(14) NOT NULL,
    TIPO CHAR(3) NOT NULL,
    MONEDA CHAR(3) NOT NULL,
    NOMBRE NVARCHAR(40) NOT NULL,
    SALDO DECIMAL(12,2) NOT NULL DEFAULT 0,

    CONSTRAINT PK_CUENTA
        PRIMARY KEY (NRO_CUENTA),

    CONSTRAINT FK_CUENTA_MONEDA
        FOREIGN KEY (MONEDA)
        REFERENCES MONEDA(CODIGO),

-- RESTRICCIONES / VALIDACIONES
    CONSTRAINT CK_CUENTA_TIPO
        CHECK (TIPO IN ('AHO', 'CTE')),

    CONSTRAINT CK_CUENTA_NUMERO
        CHECK (NRO_CUENTA NOT LIKE '%[^0-9]%'),

    CONSTRAINT CK_CUENTA_LONGITUD
        CHECK (
            (TIPO = 'CTE' AND LEN(NRO_CUENTA) = 13)
            OR
            (TIPO = 'AHO' AND LEN(NRO_CUENTA) = 14)
        ),

    CONSTRAINT CK_CUENTA_SALDO
        CHECK (SALDO >= 0)
);
GO

--TABLA MOVIMIENTO

CREATE TABLE MOVIMIENTO (
    NRO_CUENTA NVARCHAR(14) NOT NULL,
    FECHA DATETIME NOT NULL,
    TIPO CHAR(1) NOT NULL,
    IMPORTE DECIMAL(12,2) NOT NULL,

    CONSTRAINT PK_MOVIMIENTO
        PRIMARY KEY (NRO_CUENTA, FECHA),

    CONSTRAINT FK_MOVIMIENTO_CUENTA
        FOREIGN KEY (NRO_CUENTA)
        REFERENCES CUENTA(NRO_CUENTA),

--RESTRICCIONES VALIDACIONES
    CONSTRAINT CK_MOVIMIENTO_TIPO
        CHECK (TIPO IN ('D', 'A')),

    CONSTRAINT CK_MOVIMIENTO_IMPORTE
        CHECK (IMPORTE > 0)
);
GO

--TABLA TIPO_CAMBIO

CREATE TABLE TIPO_CAMBIO (
    MONEDA_ORIGEN CHAR(3) NOT NULL,
    MONEDA_DESTINO CHAR(3) NOT NULL,
    FECHA DATETIME NOT NULL,
    TASA DECIMAL(12,6) NOT NULL,

    CONSTRAINT PK_TIPO_CAMBIO
        PRIMARY KEY (MONEDA_ORIGEN, MONEDA_DESTINO, FECHA),

    CONSTRAINT FK_TIPO_CAMBIO_ORIGEN
        FOREIGN KEY (MONEDA_ORIGEN)
        REFERENCES MONEDA(CODIGO),

    CONSTRAINT FK_TIPO_CAMBIO_DESTINO
        FOREIGN KEY (MONEDA_DESTINO)
        REFERENCES MONEDA(CODIGO),

--RESTRICCIONES VALICADIONES
    CONSTRAINT CK_TIPO_CAMBIO_MONEDAS
        CHECK (MONEDA_ORIGEN <> MONEDA_DESTINO),

    CONSTRAINT CK_TIPO_CAMBIO_TASA
        CHECK (TASA > 0)
);



