CREATE LOGIN USUARIO
WITH PASSWORD = 'PASSWORD';
GO

USE BD_TRANSACCIONES_LDCC;
GO

CREATE USER USUARIO FOR LOGIN USUARIO;
GO

ALTER ROLE db_datareader ADD MEMBER USUARIO;
ALTER ROLE db_datawriter ADD MEMBER USUARIO;
GO

GRANT CREATE TABLE TO USUARIO;
GRANT CREATE PROCEDURE TO USUARIO;
GRANT EXECUTE TO USUARIO;
GO