USE BD_TRANSACCIONES_LDCC;
GO


-- TABLA MONEDA
CREATE TABLE MONEDA (
    PK_ID_MONEDA_IN INT IDENTITY(1,1) NOT NULL,
    CODIGO_CH CHAR(3) NOT NULL,
    NOMBRE_VC NVARCHAR(30) NOT NULL,
    FECHA_CREACION_DT DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_MODIFICACION_DT DATETIME NOT NULL DEFAULT GETDATE(),

    CONSTRAINT PK_MONEDA
        PRIMARY KEY (PK_ID_MONEDA_IN),

    CONSTRAINT UQ_MONEDA_CODIGO
        UNIQUE (CODIGO_CH)
);
GO


-- TABLA CUENTA
CREATE TABLE CUENTA (
    PK_ID_CUENTA_IN INT IDENTITY(1,1) NOT NULL,
    FK_ID_MONEDA_IN INT NOT NULL,
    NRO_CUENTA_VC NVARCHAR(14) NOT NULL,
    TIPO_CH CHAR(3) NOT NULL,
    NOMBRE_VC NVARCHAR(40) NOT NULL,
    SALDO_DE DECIMAL(12,2) NOT NULL DEFAULT 0,
    FECHA_CREACION_DT DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_MODIFICACION_DT DATETIME NOT NULL DEFAULT GETDATE(),

    CONSTRAINT PK_CUENTA
        PRIMARY KEY (PK_ID_CUENTA_IN),
    
    CONSTRAINT FK_CUENTA_MONEDA
        FOREIGN KEY (FK_ID_MONEDA_IN)
        REFERENCES MONEDA(PK_ID_MONEDA_IN),

    CONSTRAINT UQ_CUENTA_NRO_CUENTA
        UNIQUE (NRO_CUENTA_VC),
    
    CONSTRAINT CK_CUENTA_SALDO
        CHECK (SALDO_DE >= 0)

);
GO

-- TABLA MOVIMIENTO
CREATE TABLE MOVIMIENTO (
    PK_ID_MOVIMIENTO_IN INT IDENTITY(1,1) NOT NULL,
    FK_ID_CUENTA_IN INT NOT NULL,
    FECHA_DT DATETIME NOT NULL,
    TIPO_CH CHAR(1) NOT NULL,
    IMPORTE_DE DECIMAL(12,2) NOT NULL,
    FECHA_CREACION_DT DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_MODIFICACION_DT DATETIME NOT NULL DEFAULT GETDATE(),

    CONSTRAINT PK_MOVIMIENTO
        PRIMARY KEY (PK_ID_MOVIMIENTO_IN),

    CONSTRAINT FK_MOVIMIENTO_CUENTA
        FOREIGN KEY (FK_ID_CUENTA_IN)
        REFERENCES CUENTA(PK_ID_CUENTA_IN),

    CONSTRAINT CK_MOVIMIENTO_IMPORTE
        CHECK (IMPORTE_DE > 0)

);
GO

-- TABLA TIPO_CAMBIO
CREATE TABLE TIPO_CAMBIO (
    PK_ID_TIPO_CAMBIO_IN INT IDENTITY(1,1) NOT NULL,
    FK_ID_MONEDA_ORIGEN_IN INT NOT NULL,
    FK_ID_MONEDA_DESTINO_IN INT NOT NULL,
    FECHA_DT DATETIME NOT NULL,
    TASA_DE DECIMAL(12,6) NOT NULL,
    FECHA_CREACION_DT DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_MODIFICACION_DT DATETIME NOT NULL DEFAULT GETDATE(),

    CONSTRAINT PK_TIPO_CAMBIO
        PRIMARY KEY (PK_ID_TIPO_CAMBIO_IN),

    CONSTRAINT FK_TIPO_CAMBIO_MONEDA_ORIGEN
        FOREIGN KEY (FK_ID_MONEDA_ORIGEN_IN)
        REFERENCES MONEDA(PK_ID_MONEDA_IN),

    CONSTRAINT FK_TIPO_CAMBIO_MONEDA_DESTINO
        FOREIGN KEY (FK_ID_MONEDA_DESTINO_IN)
        REFERENCES MONEDA(PK_ID_MONEDA_IN),

    CONSTRAINT CK_TIPO_CAMBIO_TASA
        CHECK (TASA_DE > 0),

    CONSTRAINT UQ_TIPO_CAMBIO_MONEDAS_FECHA
    UNIQUE (
        FK_ID_MONEDA_ORIGEN_IN,
        FK_ID_MONEDA_DESTINO_IN,
        FECHA_DT
    )
);
GO
